version: "3"
services:
  app:
    container_name: "sample-app2"
    build:
      context: ./app
    ports:
      - 3001:3000
    volumes:
      - ./app:/opt
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    tty: true

  mysql:
    container_name: "sample-mysql2"
    build:
      context: ./mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    tty: true
