- name: install rpm
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ MYSQL_VERSION }}"

- name: disable mysql8.0
  shell: yum-config-manager --disable mysql80-community

- name: enable mysql5.7
  shell: yum-config-manager --enable mysql57-community

- name: install mysqld
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-community-client
    # - mysql-community-server
# - name: copy mysqld config
#   copy:
#     src: "roles/mysql/files/{{ item.src }}"
#     dest: "/etc/{{ item.dest }}"
#     owner: root
#     group: root
#     backup: no
#     mode: 644
#   loop:
#     - { src: my.cnf, dest: . }
#   notify: restart mysqld
